# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/pfe.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PFEWindowGen(object):
    def setupUi(self, PFEWindowGen):
        PFEWindowGen.setObjectName("PFEWindowGen")
        PFEWindowGen.resize(1940, 1018)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(PFEWindowGen.sizePolicy().hasHeightForWidth())
        PFEWindowGen.setSizePolicy(sizePolicy)
        PFEWindowGen.setMaximumSize(QtCore.QSize(9999, 9999))
        self.centralwidget = QtWidgets.QWidget(PFEWindowGen)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.expMtrTW = QtWidgets.QTableWidget(self.centralwidget)
        self.expMtrTW.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.expMtrTW.sizePolicy().hasHeightForWidth())
        self.expMtrTW.setSizePolicy(sizePolicy)
        self.expMtrTW.setMinimumSize(QtCore.QSize(0, 480))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.expMtrTW.setFont(font)
        self.expMtrTW.setObjectName("expMtrTW")
        self.expMtrTW.setColumnCount(0)
        self.expMtrTW.setRowCount(0)
        self.expMtrTW.horizontalHeader().setCascadingSectionResizes(True)
        self.expMtrTW.horizontalHeader().setDefaultSectionSize(180)
        self.expMtrTW.horizontalHeader().setMinimumSectionSize(30)
        self.expMtrTW.horizontalHeader().setSortIndicatorShown(False)
        self.expMtrTW.horizontalHeader().setStretchLastSection(False)
        self.expMtrTW.verticalHeader().setMinimumSectionSize(31)
        self.verticalLayout.addWidget(self.expMtrTW)
        PFEWindowGen.setCentralWidget(self.centralwidget)

        self.retranslateUi(PFEWindowGen)
        QtCore.QMetaObject.connectSlotsByName(PFEWindowGen)

    def retranslateUi(self, PFEWindowGen):
        _translate = QtCore.QCoreApplication.translate
        PFEWindowGen.setWindowTitle(_translate("PFEWindowGen", "Матрица ПФЭ"))
